// <auto-generated />
namespace PASSION_PROJECT_ORDER_MANAGEMENT_APP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ordermenucustomer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ordermenucustomer));
        
        string IMigrationMetadata.Id
        {
            get { return "202406131210275_order-menu-customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
